#!/bin/bash

cppcheck --error-exitcode=1 \
    cobc.c \
    cobc.h \
    codegen.c \
    codeoptim.c \
    config.c \
    error.c \
    field.c \
    help.c \
    parser.c \
    parser.h \
    pplex.c \
    ppparse.c \
    ppparse.h \
    replace.c \
    scanner.c \
    tree.c \
    tree.h \
    typeck.c
    # reserved.c \ -- this file contains errors
