name: test
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]
    
jobs:
  run-tests:
    strategy:
      matrix:
        os: ["ubuntu:22.04"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:
        
      - name: Install dependencies on Ubuntu 22.04
        if: matrix.os == 'ubuntu:22.04'
        run: apt update -y

      - name: Install prerequisite softwares
        run: |
          apt-get install -y build-essential
          apt-get install -y libncurses6 libncurses-dev ncurses-doc libgmp10 libgmp-dev m4 libtool help2man pkg-config gettext automake autoconf libxml2 libxml2-dev libxml2-utils libcjson1 libcjson-dev

      - name: Install Berkeley DB
        run: apt-get install -y libdb-dev
      
      - name: Install Berleley DB test
        run: |
          wget http://download.oracle.com/berkeley-db/db-18.1.40.tar.gz
          tar xvfz db-18.1.40.tar.gz
          cd db-18.1.40/build_unix
          ../dist/configure --prefix=/usr/local/berkeleydb/18_1_40
          make
          make install

  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: configure
        run: ./configure

      - name: make
        run: make
      
      - name: make check
        run: make check

      - name: make test
        run: make test

  static-analysis:
    runs-on: ubuntu-latest
    steps:

      - name: Install splint
        run: sudo apt-get install splint
