name: test
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    types: [opened, reopened, review_requested, synchronize]
    
jobs:
  build:

  runs-on: ubuntu-latest

  steps: 
    - uses: actions/checkout@3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck