name: test
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]
    
jobs:
  run-tests:
    strategy:
      matrix:
        os: ["ubuntu:22.04"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:
        
      - name: Install dependencies on Ubuntu 22.04
        if: matrix.os == 'ubuntu:22.04'
        run: apt update -y

      - name: Install GnuCOBOL3
        run: apt install -y gnucobol3
      
      - name: Install prerequisite softwares
        run: apt-get install -y libncurses6 libncurses-dev ncurses-doc libgmp10 libgmp-dev m4 libtool help2man pkg-config gettext automake autoconf libxml2 libxml2-dev libxml2-utils libcjson1 libcjson-dev build-essential

      - name: Install Berkeley DB
        run: apt-get install -y libdb-dev

      - uses: actions/checkout@v2
      - name: configure vbisam
        run: |
          cd vbisam
          ./configure
          sudo make
          make install
          cd ..

      - name: configure
        run: ./configure --with-vbisam

      - name: make
        run: sudo make
      
      - name: make check
        run: make check

      - name: make test
        run: make test

  static-analysis:
    runs-on: ubuntu-latest
    steps:

      - name: Install splint
        run: sudo apt-get install splint