name: test
on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]
    
jobs:
  run-tests:
    strategy:
      matrix:
        os: ["ubuntu:22.04"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:
        
      - name: Install dependencies on Ubuntu 22.04
        if: matrix.os == 'ubuntu:22.04'
        run: |
          apt update -y
          apt install -y default-jdk build-essential bison flex gettext texinfo automake autoconf

  build:

    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@3
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck