name: cppcheck

on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Install prerequisite softwares
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cppcheck

      - uses: actions/checkout@v4

      - name: Check cobc/
        working-directory: cobc/
        run: ./cppcheck

      - name: Check libcob/
        working-directory: libcob/
        run: ./cppcheck

      - name: Check bin/
        working-directory: bin/
        run: ./cppcheck